### ISSUE TITLE
Idea: Reduce the number of log lines?

### ISSUE THREAD

**Issue by EmilPhoto** [hackerfactor/nuzzle#4]
With an extreme number of incoming packets, the log grows considerably. It would be very helpful to log only the first of a series of incoming packets from the same IP. On the switch, nuzzle would compare the IP with the IP of the previous packet and only write the packet with the changed IP to the log. For detection purposes using fail2ban, such a reduced log would be sufficient.

**Comment by hackerfactor** [comment]
Good idea. Are you only interested in new IPs? Or also new ports?

**Comment by hackerfactor** [comment]
I think syslog filters are probably hat you want.
https://www.syslog-ng.com/community/b/blog/posts/syslog-ng-101-part-9-filters

**Comment by hackerfactor** [comment]
I spoke to a few folks who are using Nuzzle. The consensus is that it is a mistake to have Nuzzle filter.
- Duplicate ip+port are already collected and combined by syslog.
- Same ip with different port should not be filtered since it provides information about the attacker.
- Filtering can be done with syslog filters.
- There are also concerns about configuration options. E.g., How many IPs should be tracked? How much time should pass before seeing the same IP is logged again? It's better if each user configures their own filters since any default rules won't work well with different users.
- Assume Nuzzle tracks a long list of IPs. That slows down the processing time and increases CPU resources. It could end up missing packets.

I'm going to close this out as "no change" since (1) any solution is not a good fit for being inside Nuzzle, and (2) there are filtering options outside of Nuzzle.

**Comment by EmilPhoto** [comment]
I’m interested on IPs only, because of fail2ban "pre-crime".

My idea was much simpler.
- 1st packet arrives, nuzzle writes the IP from the packet to the log and defines lastIP = IP
- 2nd packet arrives, nuzzle compares the IP from the packet with lastIP, if they are equal, it does nothing
- 3rd packet arrives, nuzzle compares the IP from the packet with lastIP, if they do not match, writes the IP from the packet to the log and defines lastIP = IP

No history, just last IP. I assume that if an attacker scans my server, then it usually scans the whole series of ports. In the log you can see it as a series of similar lines, where only the time and ports on either side differing.

Thank you for pointing me to the syslog.

**Comment by hackerfactor** [comment]
In my experience:
1. There's a constant high level of "noise" scanning (or blind attacking) the server. The "LastIP" approach won't be very effective.
2. When there's a high volume attack, the attackers often use multiple IP addresses. (It's hard to get high-volume from a single IP.) Again, LastIP won't help here.

Don't get me wrong -- this is a good train of thought. But it needs more fleshing out before it can be practical to implement.

A better approach is to write your own syslog filter that combines lines based on IP address alone.
